### ISSUE TITLE
Bad demo link

### ISSUE THREAD

**Issue by winkler1** [remyyounes/fractalizeru#1]
Cool project! I was @reactweek also... :)

http://remyyounes.github.io/fractalizeru/ is 404... guess it's https://infinite-gorge-7152.herokuapp.com/? Any reason to host on heroku over GHP? The spinup time is always a bit annoying...

**Comment by remyyounes** [comment]
Oh, thanks!
I just didn't have time to get it working on gh pages. I'll give it a try soon.

**Comment by remyyounes** [comment]
fixed http://remyyounes.github.io/fractalizeru/
